helm: Initial "bare bones" chart configuration.
kubernetes-sigs/security-profiles-operator pull request #1013
Opened 2022-06-30 20:55 UTC by stephen-fox

This is a very, very basic helm chart configuration that consists
of the original k8s "deploy/operator.yaml" file. That file has
been broken out into separate CRDs (under "crds/").

TODOs:

  - Implement templating syntax where required
  - Write documentation about helm chart usage
  - Decide what to do about cert-manager
  - Investigate what happens when the chart is installed
    without cert-manager being present (this appears to
    cause breakage - I have not looked into it thoroughly)

In regards to cert-manager: the project's maintainers do not
support helm's dependency management feature. Speaking with
@JAORMX, we will likely need to document it as a requirement.
Refer to the following URLs for more information:

  - https://discuss.kubernetes.io/t/installing-helm-charts-cert-manager-as-a-dependency-of-my-chart-application/6170
  - https://github.com/cert-manager/cert-manager/pull/2964

#### What type of PR is this?

#### What this PR does / why we need it:

#### Which issue(s) this PR fixes:

#### Does this PR have test?

#### Special notes for your reviewer:

#### Does this PR introduce a user-facing change?

```release-note

```

2022-07-01 05:58 UTC, saschagrunert commented
Hey @stephen-fox, thank you for this contribution! May I ask you to sign your commits via EasyCLA?

2022-07-05 17:52 UTC, stephen-fox commented
Hi @saschagrunert - will do. I am just waiting for approval from my organization.

2022-07-11 13:18 UTC, JAORMX reviewed
This is a good start. Let's start looking into having a least a linting job for this, an subsequently a test scenario that uses the helm chart.

2022-07-11 13:50 UTC, JAORMX commented
/retest

2022-07-12 07:24 UTC, JAORMX commented
/retest

2022-07-12 07:38 UTC, pjbgf reviewed
@stephen-fox really good stuff, thanks for working on this. :bow: 

It would be great to have a way to ensure the Chart contents does not drift too much from the artefacts within `deploy/`. What are your thoughts on updating Makefile's `verify` target to check that the chart's `crds/operator.yaml` is aligned with the contents of the latest version of `deploy/base/crd.yaml`?

2022-07-12 07:46 UTC, saschagrunert commented
/retest

2022-07-12 07:55 UTC, saschagrunert approved these changes
Great work, I like that!

I think we need a CI job for checking consistency of the helm chart compared to the customize deployment. Not sure how to do that in detail, but we can follow-up on it. 

PTAL @jhrozek @JAORMX @pjbgf

2022-07-12 07:55 UTC, saschagrunert commented on charts/security-profiles-operator/Chart.yaml
> +appVersion: "0.4.3"
We have to update the `release.md` docs that this version has to be bumped as well.

2022-07-12 07:55 UTC, saschagrunert commented on charts/security-profiles-operator/values.yaml
> +  readOnlyRootFilesystem: true
I think changing those may break the operator, right? So do we wanna make it not configurable?

2022-07-12 07:55 UTC, saschagrunert commented
/hold

2022-07-12 13:43 UTC, stephen-fox commented
Completely agree with @pjbgf and @ccojocar about configuration drift being a problem here.

Let me take a look at the blog Cosmin linked.

2022-07-12 21:05 UTC, stephen-fox commented
Unrelated to config drift - it looks like helm does not support updating or deleting CRDs. Is this a problematic for the operator? (https://helm.sh/docs/chart_best_practices/custom_resource_definitions/#some-caveats-and-explanations)

2022-07-13 07:11 UTC, saschagrunert commented
> Unrelated to config drift - it looks like helm does not support updating or deleting CRDs. Is this a problematic for the operator? (https://helm.sh/docs/chart_best_practices/custom_resource_definitions/#some-caveats-and-explanations)

Yeah we would graduate our APIs to stable slowly which could incorporate a CRD update.

2022-07-18 08:20 UTC, saschagrunert commented
@JAORMX @pjbgf I'm kinda fine with the overall approach, what do you think in relation to @stephen-fox's [comment](https://github.com/kubernetes-sigs/security-profiles-operator/pull/1013#issuecomment-1185927152)?

2022-07-19 07:10 UTC, saschagrunert commented
/retest

2022-07-19 07:18 UTC, JAORMX requested changes
I like the overall approach. I'd say we should also make the Deployment/Pod labels configurable, and it's ready IMO.

2022-07-19 21:02 UTC, stephen-fox commented
/retest

2022-07-20 06:34 UTC, saschagrunert commented
/retest

2022-07-20 08:17 UTC, saschagrunert commented
/retest

2022-07-20 10:44 UTC, saschagrunert commented
> @saschagrunert any idea why the olm test broke? Seems to me like it's a legitimate issue.

Yes I think the operator bundle is broken with that change :thinking:

2022-07-20 19:50 UTC, stephen-fox commented
/retest

2022-07-21 13:14 UTC, stephen-fox commented
Hmm, it's still broken. I'll keep digging into the `make bundle` code.

2022-07-21 19:08 UTC, stephen-fox commented
I think I understand at least some of the problem now. The `make bundle` automation `cat`s `deploy/operator.yaml` into the operator-sdk. Since I removed the `Deployment` resource from that file, it ends up missing from the OLM bundle. I am not sure about `clusterserviceversion.yaml`, but I would not be surprised if the missing resource has side effects on that.

2022-07-26 16:38 UTC, stephen-fox commented
ps: Changes rebased on `main`.

2022-07-27 11:13 UTC, saschagrunert commented
@stephen-fox please rebase again to get the latest CI changes in :)

2022-07-27 16:16 UTC, JAORMX commented
/hold cancel

2022-07-27 16:16 UTC, JAORMX commented
This lgtm

2022-07-27 16:23 UTC, JAORMX commented
/approve

2022-07-27 16:24 UTC, JAORMX approved these changes

2022-07-27 17:28 UTC, merged