Do vulnerability scans on images built on CI
kubernetes-sigs/security-profiles-operator pull request #1090
Opened 2022-08-15 11:25 UTC by JAORMX

#### What type of PR is this?

/kind cleanup

#### What this PR does / why we need it:

This introduces Trivy [1] to do vulnerability scans after building
images.

These scans can alert us to know when a tag bump is needed or when we're
misconfiguring an image.

[1] https://aquasecurity.github.io/trivy

#### Which issue(s) this PR fixes:

None

#### Does this PR have test?

The image build tests

#### Special notes for your reviewer:

#### Does this PR introduce a user-facing change?

```release-note
NONE
```

2022-08-15 18:09 UTC, pjbgf approved these changes
/lgtm

2022-08-15 18:23 UTC, pjbgf commented
Not sure whether the action supports a way in which it can access the image without using UNIX sockets:

```
FATAL	image scan error: scan error: unable to initialize a scanner: unable to initialize a docker scanner: 4 errors occurred:
	* unable to inspect the image (build): Error: No such image: build
	* unable to initialize Podman client: no podman socket found: stat podman/podman.sock: no such file or directory
	* containerd socket not found: /run/containerd/containerd.sock
	* GET https://index.docker.io/v2/library/build/manifests/latest: UNAUTHORIZED: authentication required; [map[Action:pull Class: Name:library/build Type:repository]]
```

2022-08-16 06:59 UTC, JAORMX commented
@pjbgf if this doesn't work out, I can use Grype instead, it has an action that should work without sockets IIRC.

2022-08-19 08:03 UTC, pjbgf commented on .github/workflows/build.yml
> +        uses: docker/setup-buildx-action@v2
I think for most things we are using the hash commit as version:
```suggestion
        uses: docker/setup-buildx-action@312f67c6629946ba17269558b63d0bd84a63caab
```

2022-08-19 08:41 UTC, pjbgf commented
/retest

2022-08-19 08:45 UTC, pjbgf requested changes
Let's align the action versions with the rest of the workflow which use hash version, then we can benefit from hermetic workflows.

Dependabot will keep this updated for us.

2022-08-19 08:45 UTC, pjbgf commented on .github/workflows/build.yml
> +        uses: docker/setup-buildx-action@v2
```suggestion
        uses: docker/setup-buildx-action@312f67c6629946ba17269558b63d0bd84a63caab
```

2022-08-19 10:47 UTC, pjbgf reviewed
There are a few more actions that we can set their hash versions.

2022-08-19 10:47 UTC, pjbgf commented on .github/workflows/build.yml
> +        uses: docker/build-push-action@v3
```suggestion
        uses: docker/build-push-action@965c6a410d446a30e95d35052c67d6eded60dad6
```

2022-08-19 10:47 UTC, pjbgf commented on .github/workflows/build.yml
> +        uses: aquasecurity/trivy-action@master
```suggestion
        uses: aquasecurity/trivy-action@d63413b0a4a4482237085319f7f4a1ce99a8f2ac
```

2022-08-19 10:47 UTC, pjbgf commented on .github/workflows/build.yml
> +        uses: docker/setup-buildx-action@v2
```suggestion
        uses: docker/setup-buildx-action@dc7b9719a96d48369863986a06765841d7ea23f6
```

2022-08-19 10:47 UTC, pjbgf commented on .github/workflows/build.yml
> +        uses: docker/login-action@v2
```suggestion
        uses: docker/login-action@49ed152c8eca782a232dede0303416e8f356c37b
```

2022-08-19 10:47 UTC, pjbgf commented on .github/workflows/build.yml
> +        uses: docker/metadata-action@v4
```suggestion
        uses: docker/metadata-action@69f6fc9d46f2f8bf0d5491e4aabe0bb8c6a4678a
```

2022-08-19 10:47 UTC, pjbgf commented on .github/workflows/build.yml
> +        uses: docker/build-push-action@v3
```suggestion
        uses: docker/build-push-action@c84f38281176d4c9cdb1626ffafcd6b3911b5d94
```

2022-08-19 10:47 UTC, pjbgf commented on .github/workflows/build.yml
> +        uses: aquasecurity/trivy-action@master
```suggestion
        uses: aquasecurity/trivy-action@d63413b0a4a4482237085319f7f4a1ce99a8f2ac
```

2022-08-19 10:47 UTC, pjbgf commented on .github/workflows/build.yml
> +        uses: docker/login-action@v2
```suggestion
        uses: docker/login-action@d398f07826957cd0a18ea1b059cf1207835e60bc
```

2022-08-19 12:47 UTC, pjbgf approved these changes
/lgtm

great job @JAORMX, thanks for working on this. :bow:

2022-08-19 13:54 UTC, merged