Bump fedora cloud VM to version 34
kubernetes-sigs/security-profiles-operator pull request #425
Opened 2021-04-28 14:51 UTC by saschagrunert

#### What type of PR is this?

/kind cleanup

#### What this PR does / why we need it:
None
#### Which issue(s) this PR fixes:

None
#### Does this PR have test?
None

#### Special notes for your reviewer:
None
#### Does this PR introduce a user-facing change?

```release-note
None
```

2021-04-28 14:55 UTC, JAORMX approved these changes

2021-04-29 10:36 UTC, saschagrunert commented
The selinux init container is complaining:

```
+ semodule -i /usr/share/selinuxd/templates/base_container.cil /usr/share/selinuxd/templates/config_container.cil /usr/share/selinuxd/templates/home_container.cil /usr/share/selinuxd/templates/log_container.cil /usr/share/selinuxd/templates/net_container.cil /usr/share/selinuxd/templates/tmp_container.cil /usr/share/selinuxd/templates/tty_container.cil /usr/share/selinuxd/templates/virt_container.cil /usr/share/selinuxd/templates/x_container.cil
error parsing semanage configuration file: syntax error
semodule:  Could not create semanage handle
+ semodule -i /opt/spo-profiles/selinuxd.cil
error parsing semanage configuration file: syntax error
semodule:  Could not create semanage handle
```

2021-04-29 11:30 UTC, saschagrunert commented
Switched to the selinuxd-fedora image for now.

2021-04-29 12:02 UTC, saschagrunert commented
/retest

2021-04-29 12:06 UTC, JAORMX requested changes

2021-04-29 12:06 UTC, JAORMX commented on test/suite_test.go
> +	selinuxdImage    = "quay.io/jaosorior/selinuxd-fedora"
This won't work in OpenShift.

2021-04-29 12:09 UTC, saschagrunert commented on test/suite_test.go
> +	selinuxdImage    = "quay.io/jaosorior/selinuxd-fedora"
Reverted the changes to this file.

2021-05-04 11:16 UTC, closed without merging