Create draft version of AppArmor CRD
kubernetes-sigs/security-profiles-operator pull request #643
Opened 2021-11-05 17:17 UTC by pjbgf

#### What type of PR is this?
/kind feature
/kind api-change

#### What this PR does / why we need it:
Add support for representing AppArmor profiles as CRD.
This reuses #176 and therefore is marked as `Co-authored-by:` @Kaizhe

#### Which issue(s) this PR fixes:
Relates to #126 

#### Does this PR have test?
N/A

#### Special notes for your reviewer:
Reconciler code will be part of a follow-up PR.

The [discussion](https://github.com/kubernetes-sigs/security-profiles-operator/pull/176/files#r545294474) around representing AppArmor profiles in a `structured` vs `unstructured` manner is still up for debate.
Considering this is in `alpha`, the idea was to go ahead implementing the basic behaviour as-is and review it once the functionality is mature enough.

#### Does this PR introduce a user-facing change?

```release-note
Add CRD type to represent AppArmor profiles.
```

2021-11-05 17:41 UTC, pjbgf commented
@Kaizhe thank you for the original contribution, please have a look.

@saschagrunert @cmurphy @JAORMX @jhrozek please share your thoughts

2021-11-08 07:14 UTC, JAORMX requested changes

2021-11-08 07:14 UTC, JAORMX commented on examples/apparmorprofile.yaml
> +  name: apparmorprofile-sample
could you add a simple description of what this does as an annotation here?

2021-11-08 08:33 UTC, saschagrunert reviewed
Thanks for taking this over @pjbgf! Happy to lgtm if @JAORMX comment got addressed.

2021-11-08 09:17 UTC, pjbgf commented
@saschagrunert @JAORMX changed it accordingly - PTAL

2021-11-08 09:21 UTC, JAORMX approved these changes

2021-11-08 10:41 UTC, saschagrunert approved these changes

2021-11-08 17:10 UTC, pjbgf commented
/test pull-security-profiles-operator-test-e2e

2021-11-08 17:15 UTC, pjbgf commented
@JAORMX @saschagrunert is the e2e-fedora error is intermittent? is there a way to rerunning it without having to rerun all the git actions tests? 
```
Error:      	Expected nil, but got: command /root/go/src/k8s.io/kubernetes/_output/bin/kubectl -n security-profiles-operator wait --timeout 120s --for condition=ready spod spod did not succeed: error: timed out waiting for the condition on securityprofilesoperatordaemons/spod
```

2021-11-08 23:12 UTC, merged

2021-11-09 08:25 UTC, saschagrunert commented
> is there a way to rerunning it without having to rerun all the git actions tests?

No I don't think GitHub actions supports that for now.