fix: disable selinux from SPOD security context when selinux is not in enforcing mode
kubernetes-sigs/security-profiles-operator pull request #828
Opened 2022-03-10 10:41 UTC by ccojocar

Signed-off-by: Cosmin Cojocar <gcojocar@adobe.com>

#### What type of PR is this?

#### What this PR does / why we need it:

#### Which issue(s) this PR fixes:

#### Does this PR have test?

#### Special notes for your reviewer:

#### Does this PR introduce a user-facing change?

```release-note

```

2022-03-10 11:25 UTC, saschagrunert commented
/ok-to-test

2022-03-10 11:45 UTC, saschagrunert commented
/retest

2022-03-10 11:46 UTC, saschagrunert reviewed
I think we can add a release note for this :) 

Otherwise
/lgtm

2022-03-10 12:51 UTC, jhrozek commented
lgtm also. I honestly don't see why did the fedora e2e test fail, all invidivual tests show either as pass or skip..

2022-03-10 14:16 UTC, ccojocar commented
> I think we can add a release note for this :)

@saschagrunert How do I add a release note? Thanks

2022-03-10 14:17 UTC, saschagrunert commented
> > I think we can add a release note for this :)
> 
> @saschagrunert How do I add a release note? Thanks

By adding it to the ```release-note block in the PR

2022-03-10 14:29 UTC, ccojocar commented
Thanks @saschagrunert, I added a brief release note.

2022-03-11 07:40 UTC, JAORMX commented
@ccojocar Flatcar is working on upgrading to a newer SELinux ref policy which includes `spc_t`. Currently though, containers there rely on the virt modules for labeling. So, while `spc_t` might not be there. e.g. in the Flatcar policy that's being used, `container_t` does not exist, and instead there's `svirt_lxc_net_t`. There might be an alternative label that represents `spc_t`, I'm looking at options. However, instead of turning SELinux options off; why not disable SELinux support in the SPO instead? We do have a configuration flag for this, and thus it wouldn't deploy the SELinux bits.

2022-03-11 07:41 UTC, JAORMX requested changes

2022-03-11 07:41 UTC, JAORMX commented on internal/pkg/manager/spod/setup.go
> +	}
I don't think we should be doing this, instead you could just turn off SELinux in the SPO deployment.

2022-03-11 10:13 UTC, ccojocar commented
/test all

2022-03-11 10:21 UTC, ccojocar commented
>  However, instead of turning SELinux options off; why not disable SELinux support in the SPO instead? We do have a configuration flag for this, and thus it wouldn't deploy the SELinux bits.

@JAORMX You misunderstood the fix. This is not related to SELinux container which manage the SELinux profile. I am aware that that option can be turned off and it is turned off by default. 

The issue is that `spc_t` is hardcoded in deployment for all containers part of SPOD daemon. Including the daemon container itself. This doesn't work on a Linux distribution which doesn't support this SELinux type. Also it doesn't make sense to be there if SELinux is not in enforcement mode on k8s nodes.

2022-03-11 11:17 UTC, JAORMX commented
> The issue is that `spc_t` is hardcoded in deployment for all containers part of SPOD daemon. Including the daemon container itself. This doesn't work on a Linux distribution which doesn't support this SELinux type.

I understand  this; in that sense, it makes sense not to require this or make this configurable in the SPO.

> Also it doesn't make sense to be there if SELinux is not in enforcement mode on k8s nodes.

I, however, don't agree with this statement. Turning SELinux to `enforcing` would be disruptive in deployments that do have `spc_t` and would require re-deploying the SPO as the pods would need to be relabeled. e.g. this would be problematic in Openshift. I wonder if we can come to a solution that doesn't cause this issue.

2022-03-11 13:41 UTC, ccojocar commented
> I understand this; in that sense, it makes sense not to require this or make this configurable in the SPO.

The initial solution in #826 was to make the security context of each container part of SPO configurable. I think there was a concern that this is exposing too much the API in the CRD.

2022-03-11 14:04 UTC, JAORMX commented
@ccojocar sorry for the confusion. I'll reach out to the other maintainers and we'll get this sorted. Thanks a lot for the contributions!

2022-03-14 08:24 UTC, saschagrunert commented
Started a discussion in https://kubernetes.slack.com/archives/C013FQNB0A2/p1647006231779659

2022-03-14 11:12 UTC, ccojocar commented
/test all

2022-03-15 09:10 UTC, ccojocar commented
/test all

2022-03-15 14:29 UTC, saschagrunert approved these changes

2022-03-15 15:34 UTC, ccojocar commented
/test e2e-fedora

2022-03-15 15:35 UTC, ccojocar commented
/test pull-security-profiles-operator-test-e2e

2022-03-15 15:37 UTC, ccojocar commented
/test all

2022-03-17 10:02 UTC, ccojocar commented
/test pull-security-profiles-operator-build-image

2022-03-21 09:40 UTC, ccojocar commented
Closing this in favour of https://github.com/kubernetes-sigs/security-profiles-operator/pull/850. 

The SELinux configuration cannot be detected in the manager container because it requires to mount the SELinux pseudo file system which will entitle some additional privileges which needs to be granted to the manager container. Discussion in https://kubernetes.slack.com/archives/C013FQNB0A2/p1647525440776799

2022-03-21 09:40 UTC, closed without merging