feat: make the selinux type configurable in the SPOD CRD
kubernetes-sigs/security-profiles-operator pull request #851
Opened 2022-03-21 14:22 UTC by ccojocar

Signed-off-by: Cosmin Cojocar <gcojocar@adobe.com>

#### What type of PR is this?

#### What this PR does / why we need it:

#### Which issue(s) this PR fixes:

#### Does this PR have test?

#### Special notes for your reviewer:

#### Does this PR introduce a user-facing change?

```release-note

```

2022-03-21 14:29 UTC, ccojocar commented on api/spod/v1alpha1/spod_types.go
> +	SelinuxTypeTag string `json:"selinuxTypeTag,omitempty"`
release not is added, I'll update the docs

2022-03-21 14:34 UTC, JAORMX requested changes

2022-03-21 14:46 UTC, ccojocar commented on api/spod/v1alpha1/spod_types.go
> +	SelinuxTypeTag string `json:"selinuxTypeTag,omitempty"`
I added as well a section into the docs.

2022-03-21 14:49 UTC, ccojocar commented on api/spod/v1alpha1/spod_types.go
> +	// +optional
I added the default value.

2022-03-21 15:39 UTC, ccojocar commented
@saschagrunert @JAORMX I fixed all review comments and the tests passed. Please could you have another look? Thanks

2022-03-22 07:01 UTC, JAORMX approved these changes
/lgtm

This is a great addition! thanks for working on this

2022-03-22 07:17 UTC, merged